### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by rsimkin** [turbanoff/CommitMessageChecker#1]
I have installed this plugin on PHPStorm 2018.1.6, but i can commit any message indepent of branch name.
Checkbox "Check reference to issue in message" is checked.

Help please what i need to do?

**Comment by turbanoff** [comment]
@rsimkin Did you configured VCS regexps?
It can be done in 'File | Settings | Version Control | Issue Navigation'
Example for our JIRA:
![image](https://user-images.githubusercontent.com/741251/51920484-8f066a00-23f6-11e9-9844-b2816695033d.png)

**Comment by rsimkin** [comment]
Thanks!

**Comment by kortov** [comment]
I think it should be written in info. Because it's not obvious and not everybody knows about this feature. I guess this link [Idea help](https://www.jetbrains.com/help/idea/handling-issues.html) would be helpful
